### ISSUE TITLE
Is there anyway to allow me to show all the HTTP headers or body?

### ISSUE THREAD

**Issue by fanchangyong** [jbittel/httpry#10]
With the -f format option,I could select which header to output,but what should I do if I want to show all the headers send and receive?

**Comment by jbittel** [comment]
Currently there's no way to display all headers at once, without specifying each one in the format string. It's a feature I've considered adding, but it never made it high enough on the list as the primary use case involves extracting specific, predetermined fields. Still, I can see where it would  be helpful in some instances.

**Comment by iSWORD** [comment]
Any progress on this?
