### ISSUE TITLE
ppp support

### ISSUE THREAD

**Issue by justinpitts** [jbittel/httpry#5]
Any chance you could support listening on a ppp interface?

**Comment by jbittel** [comment]
I've pushed a53843f7242d9183eec0e7adb3ff215d98a50a86 which adds support for PPP link offsets. However, I don't have an easy way to test it, nor can I seem to find a good pcap to verify the behavior. If you could give it a try and let me know if it works for you or not, that would be very helpful.

Thanks!

**Comment by justinpitts** [comment]
Works!
Many thanks. This is useful to me on a daily basis.

**Comment by jbittel** [comment]
Excellent, thanks for letting me know!
